# This workflow is only intended to run when a pull-request is merged into the main branch
name: Main branch AaC Workflow

on:
  push:
    branches: [main]

jobs:
  Build_Package_and_Artifacts:
    uses: jondavid-black/AaC/.github/workflows/build-artifacts.yml@1e3f89c23eb6583116848d81ccd5ad952f9a62b6

  Run_Functional_Tests:
    needs: Build_Package_and_Artifacts
    uses: jondavid-black/AaC/.github/workflows/functional-tests.yml@d280c4fc448c14366d4abf1f1cc0d8bd2c38b047
  Deploy_Artifacts:
    needs: Run_Functional_Tests
    uses: jondavid-black/AaC/.github/workflows/deploy-artifacts.yml@1e3f89c23eb6583116848d81ccd5ad952f9a62b6
