# This workflow is only intended to run when a pull-request is merged into the main branch
name: Main branch AaC Workflow

on:
  push:
    branches: [main]

jobs:
  Build_Package_and_Artifacts:
    uses: jondavid-black/AaC/.github/workflows/build-artifacts.yml@2f31748af5e838d581bfce55111a76ee5c8d0add

  Run_Functional_Tests:
    needs: Build_Package_and_Artifacts
    uses: jondavid-black/AaC/.github/workflows/functional-tests.yml@6201f400dbca7f90f7206e1b73ccd9e9470e417a
    # uses: jondavid-black/AaC/.github/workflows/functional-tests.yml@80bdd88b0d35b04c14d7e54d4c1de1c3f2ef0e69
