# This workflow is intended to run for ANY pull request
name: Pull Requests AaC Workflow

on:
  pull_request:

jobs:
  Build_Package_and_Artifacts:
    uses: jondavid-black/AaC/.github/workflows/build-artifacts.yml@0ac1c437f1fe8a071857b932fcf292e736f57c75

  Run_Functional_Tests:
    needs: Build_Package_and_Artifacts
    uses: jondavid-black/AaC/.github/workflows/functional-tests.yml@9e0ff39886f7a0ce54e6eac6c6f2d78f9f9f1254