# This workflow is intended to run for ANY pull request
name: Pull Requests AaC Workflow

on:
  pull_request:

jobs:
  Build_Package_and_Artifacts:
    uses: jondavid-black/AaC/.github/workflows/build-artifacts.yml@1e3f89c23eb6583116848d81ccd5ad952f9a62b6

  Run_Functional_Tests:
    needs: Build_Package_and_Artifacts
    uses: jondavid-black/AaC/.github/workflows/functional-tests.yml@6ee0e7e59609550adb8296e2e2638d47d2382181

